### ISSUE TITLE
Выпилить не нужные файлы из сборки

### ISSUE THREAD

**Issue by dolpheen** [usford/Traffic_Lights#6]
При распаковке появляются сообщения о каких-то файлах. См.скрин
Заказчик говорит, при этом, что после все работает.
Нужно уточнить, в чем может быть проблема?
Возможно эти файлы не нужны, так как выглядят как промежуточные рабочие, и, если так, может создать батник, который будет удалять их и готовить сборку rar
![shokin_files_2022-08-11 19 01 32](https://user-images.githubusercontent.com/5053583/184178619-47859792-518c-476e-a90a-1827a7ed9845.jpg)

**Comment by dolpheen** [comment]
прислали список
[ошибки архива.docx](https://github.com/usford/Traffic_Lights/files/9314426/default.docx)
@usford похоже, все таки на временные файлы. Может их по маске удалять?

**Comment by usford** [comment]
Буду удалять папку TrafficLights/obj руками
